{% set name = "dolang" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c68450cfb2ca629b38a738a188e0e7e79125c0c9a2f30493030ef4bd87ee6e4c
  patches: 
    - fix_poetry.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip ==22.2.2
    - python >=3.8,<3.11
    - poetry
  run:
    - numba >=0.57.1
    - numpy >=1.22.2
    - python >=3.8, <3.12
    - sympy >=1.11.1
    - pyyaml >=6.0
    - lark >=1.1.2

test:
  imports:
    - dolang
    - dolang.tests

about:
  home: https://github.com/EconForge/dolang.py
  license: BSD-2-Clause
  license_family: BSD
  # in the future, don't include the license file
  # as it will be part of the source distribution
  # cf: https://github.com/EconForge/dolang.py/issues/3
  license_file: COPYING
  summary: Dolo Modeling Language

extra:
  recipe-maintainers:
    - albop
