{% set name = "dolang" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35909460ddc92b9b9414b76e7d7f8166494ec1da64d9a7b121a7be68239c4e69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip ==21.0.1
    - python >=3.7
    - poetry
  run:
    - numba >=0.48.0
    - numpy >=1.18.1
    - python >=3.7
    - sympy >=1.5.1
    - pyyaml >=5.3.1
    - tempita >=0.5.2
    - lark-parser >=0.11.2

test:
  imports:
    - dolang
    - dolang.tests

about:
  home: https://github.com/EconForge/dolang.py
  license: BSD-2-Clause
  license_family: BSD
  # in the future, don't include the license file
  # as it will be part of the source distribution
  # cf: https://github.com/EconForge/dolang.py/issues/3
  license_file: COPYING
  summary: Dolo Modeling Language

extra:
  recipe-maintainers:
    - albop
